import { ModalProvider } from "@/context/ModalContext";
import { UserProvider } from "@/context/UserContext";
import ModalContainer from "@/modules/ModalContainer";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`overflow-x-hidden ${inter.className}`}>
        <UserProvider>
          <ModalProvider>
            <ModalContainer />
            {children}
            {/* Modal root for React Portal */}
            <div id="modal-root"></div>
          </ModalProvider>
        </UserProvider>
      </body>
    </html>
  );
}
